*** Settings ***
Resource  ../../../../Resources/eloadohelyek_resource.robot

Suite Setup  Open browser and login and after go to the venues page  ${OLDAL_URL}  ${bogeszo}  ${LOGIN_DATA}
Suite Teardown  Common.End web test

*** Variables ***
&{LOGIN_DATA}  email=${LOGIN_EMAIL.${DE}}  password=${LOGIN_PASSWORD.${DE}}  partner=${VARIABLES_PARTNER}  language=${LAN}
${LAN}=  En

&{DATA}  Existing=0
...      Venuname=Vinyó szerkesztes teszt ma

&{AUDITORIUMDATA1}  	Auditoriumname=Vinyó nézőtér teszt
...	                Auditoriumcapacity=20
...	                Auditoriumvenueaddress=${True}
#...	                Auditoriumcountry=Hungary
#...	                Auditoriumzipcode=3600
#...	                Auditoriumcity=Ózd
#...	                Auditoriumcounty=Borsod
#...	                Auditoriumstreet=Nap
#...	                Auditoriumhousenumber=2
#...	                Auditoriumdoor=ajtó1
#...	                Auditoriumfloor=2emelet

&{AUDITORIUMDATA2}  	Auditoriumname=Vinyó nézőtér
...	                Auditoriumcapacity=20
...	                Auditoriumvenueaddress=${True}
#...	                Auditoriumcountry=Hungary
#...	                Auditoriumzipcode=3600
#...	                Auditoriumcity=Ózd
#...	                Auditoriumcounty=Borsod
#...	                Auditoriumstreet=Nap
#...	                Auditoriumhousenumber=2
#...	                Auditoriumdoor=ajtó1
#...	                Auditoriumfloor=2emelet

&{AUDITORIUMDATA3}  	Auditoriumname=Vinyó nézőtér
...	                Auditoriumcapacity=20
...	                Auditoriumvenueaddress=${True}
#...	                Auditoriumcountry=Hungary
#...	                Auditoriumzipcode=3600
#...	                Auditoriumcity=Ózd
#...	                Auditoriumcounty=Borsod
#...	                Auditoriumstreet=Nap
#...	                Auditoriumhousenumber=2
#...	                Auditoriumdoor=ajtó1
#...	                Auditoriumfloor=2emelet

&{VENUEDATA}  Venuename=Vinyó szerkesztes teszt ma
...	          Venuedescription=Valami szerkesztett előadás
...	          Venuecountry=Hungary
...	          Venuezipcode=1144
...	          Venuecity=Jászfelsőszentgyörgy
...	          Venuecounty=Pest
...	          Venuestreet=Október huszonharmadika utca
...	          Venuehousenumber=11/D
...	          Venuedoor=41
...	          Venuefloor=10


@{AUDITORIUMS}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}
...  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}    &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA2}  &{AUDITORIUMDATA1}  &{AUDITORIUMDATA3}
&{VENUEAUDITORIUMS}  Venue=${VENUEDATA}
                ...  Audits=${AUDITORIUMS}

*** Test Cases ***
Test1
    [Tags]  most
    ${ido} =  get time in string
    ${venuedb} =  get length  ${AUDITORIUMS}
    log to console  ${venuedb}
    ${VENUEAUDITORIUMS.Venue.Venuename} =  set variable  ${VENUEAUDITORIUMS.Venue.Venuename}${ido}
    Create new venue and audits start the venues page  ${VENUEAUDITORIUMS}
    Check the new venue was created  ${VENUEAUDITORIUMS.Venue.Venuename}