*** Variables ***
&{PP_VARIABLE_INVITE_BUTTON_TEXT}  Hun=Partner meghívása  En=Invite partner
&{PP_VARIABLE_NEW_PARTNER_BUTTON_TEXT}  Hun=Új létrehozása  En=Create new
&{PP_VARIABLE_TITLE_TEXT}  Hun=Partnerek  En=Partners
&{PP_VARIABLE_PARTNER_NAME_TEXT}  Hun=Partner neve  En=Partner name
&{PP_VARIABLE_EMAIL_ADDRESS_TEXT}  Hun=E-mail cím  En=E-mail
&{PP_VARIABLE_STATUS_TEXT}  Hun=Állapot  En=Status
&{PP_VARIABLE_RESET_BUTTON_TEXT}  Hun=Visszaállítás  En=Reset
&{PP_VARIABLE_SEARCH_BUTTON_TEXT}  Hun=Keresés  En=Search
&{PP_VARIABLE_PARTNER_NAME_IN_TABLE_HEADER_TEXT}  Hun=Partner neve  En=Partner name
&{PP_VARIABLE_PARTNER_EMAILCIM_IN_TABLE_HEADER_TEXT}  Hun=E-mail cím  En=E-mail
&{PP_VARIABLE_PARTNER_CIM_IN_TABLE_HEADER_TEXT}  Hun=Cím  En=Address
&{PP_VARIABLE_PARTNER_STATUS_IN_TABLE_HEADER_TEXT}  Hun=Állapot  En=Status
&{PP_VARIABLE_PARTNER_FEATURE_IN_TABLE_HEADER_TEXT}  Hun=Lehetőségek  En=Features
&{PP_VARIABLE_PARTNER_STATUS_LISTBOX_FIRTS_ITEM_TEXT}  Hun=Összes  En=All
&{PP_VARIABLE_PARTNER_STATUS_LISTBOX_SECOND_ITEM_TEXT}  Hun=Új  En=New
&{PP_VARIABLE_PARTNER_STATUS_LISTBOX_THIRD_ITEM_TEXT}  Hun=Jóváhagyásra vár  En=Waiting for approval
&{PP_VARIABLE_PARTNER_STATUS_LISTBOX_FOURTH_ITEM_TEXT}  Hun=Aktív  En=Active
&{PP_VARIABLE_PARTNER_STATUS_LISTBOX_FIFTH_ITEM_TEXT}  Hun=Felfüggesztve  En=Suspended
&{PP_VARIABLE_PARTNER_STATUS_LISTBOX_SIXTH_ITEM_TEXT}  Hun=Törölt  En=Deleted